In [65]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

from sklearn.metrics import f1_score
from sklearn.preprocessing import Normalizer
from sklearn.metrics import confusion_matrix
from sklearn.metrics import plot_confusion_matrix


import matplotlib.pyplot as plt
import scikitplot as skplt


In [66]:
df = pd.read_csv('Iris.csv')
df.head()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [67]:
x = df.loc[:, 'Sepal_Length':'Petal_Width'].to_numpy().astype('float')
y = df['Class']

In [68]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)


In [69]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train, y_train)



KNeighborsClassifier(n_neighbors=3)

In [70]:
preds = knn.predict(x_test)


In [71]:
acc_unno = accuracy_score(y_test, preds)
f1_unno = f1_score(y_test, preds, average='micro')
print(acc_unno)
print(f1_unno)


1.0
1.0


In [72]:
norm = Normalizer().fit(x)
x_norm = norm.transform(x)


In [73]:
x_train_n, x_test_n, y_train_n, y_test_n = train_test_split(x_norm, y, test_size=0.25, random_state=42)


In [74]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train_n, y_train_n)

preds_n = knn.predict(x_test_n)


In [75]:
acc_no = accuracy_score(y_test_n, preds_n)
f1_no = f1_score(y_test_n, preds_n, average='micro')
print(acc_no)
print(f1_no)
print(confusion_matrix(y_test_n, preds_n, labels=['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']))


0.9736842105263158
0.9736842105263158
[[15  0  0]
 [ 0 11  0]
 [ 0  1 11]]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed